<a href="https://colab.research.google.com/github/Sourav-2510/intro_to_numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [15]:
b=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]],dtype='int16')

In [6]:
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [8]:
b.shape

(3, 4)

In [9]:
a.shape

(4,)

In [10]:
b.itemsize

8

In [13]:
type(a)

numpy.ndarray

In [14]:
a.dtype

dtype('int64')

In [16]:
b.dtype

dtype('int16')

In [17]:
a.nbytes

32

In [18]:
new_array=np.array([[1,2,3,4,5,6],[2,3,4,5,6,7]])

In [19]:
new_array[0][2]=4

In [20]:
new_array

array([[1, 2, 4, 4, 5, 6],
       [2, 3, 4, 5, 6, 7]])

In [36]:
lst=[]
for i in range(0,5):
  
  a=int(input())
  lst.append(a)
print(lst)

  

2
3
4
5
6
[2, 3, 4, 5, 6]


In [41]:
print(new_array[:,0])


[1 2]


In [42]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [43]:
np.full((3,5),7,dtype='float32')

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]], dtype=float32)

In [44]:
np.random.rand(2,4)

array([[0.88895719, 0.97331057, 0.18611255, 0.56723688],
       [0.58659229, 0.16473619, 0.52913013, 0.51713966]])

In [45]:
np.random.random_sample(new_array.shape)

array([[0.86066879, 0.24484434, 0.31449942, 0.80334655, 0.38235741,
        0.35115585],
       [0.79484243, 0.02851475, 0.78017369, 0.92803766, 0.01439474,
        0.10656917]])

In [46]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
arr=np.array([[12,23,34]])
a1=np.repeat(arr,3,axis=0)
a1

array([[12, 23, 34],
       [12, 23, 34],
       [12, 23, 34]])

#linear algebra

In [53]:
a=np.full((3,4),5)
a

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [52]:
b=np.full((4,5),4)

b

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [54]:
np.matmul(a,b)

array([[80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80]])

In [57]:
c=np.identity(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

determinant

In [59]:
np.linalg.det(c)

1.0

#statistic

In [61]:
s=np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.min(s)

1

In [63]:
np.max(s)

6

In [64]:
np.min(s,axis=0)

array([1, 2, 3])

In [65]:
np.min(s,axis=1)

array([1, 4])

In [66]:
np.sum(s)

21

column sum

In [67]:
np.sum(s,axis=0)

array([5, 7, 9])

row sum

In [68]:
np.sum(s,axis=1)

array([ 6, 15])

#Reorganizing arrays

In [70]:
new=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
new.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [72]:
new.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
new1=np.array([[1,2,34,45],[3,4,5,6]])
new1

array([[ 1,  2, 34, 45],
       [ 3,  4,  5,  6]])

In [75]:
new1.reshape(4,2)

array([[ 1,  2],
       [34, 45],
       [ 3,  4],
       [ 5,  6]])

In [76]:
new1.reshape(1,8)

array([[ 1,  2, 34, 45,  3,  4,  5,  6]])

vertical stacking

In [77]:
v1=np.array([2,4,6,8])
v2=np.array([1,3,5,7])

In [78]:
np.vstack([v1,v2])

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

horizontal stacking

In [79]:
np.hstack([v1,v2])

array([2, 4, 6, 8, 1, 3, 5, 7])

#import data

In [82]:
Data=np.genfromtxt('/content/sample_data/sourav.txt',delimiter=',')

In [83]:
Data

array([1., 2., 3., 4., 5.])

#boolean

In [84]:
Data>2

array([False, False,  True,  True,  True])

In [85]:
Data==2

array([False,  True, False, False, False])

In [86]:
b1=np.array([20,30,40,50,60,70,80,90])

In [88]:
b1[[2,5,4]]

array([40, 70, 60])

In [89]:
np.any(b1>30)

True